- name: First interaction
  uses: actions/first-interaction@v1.1.0
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    # Comment to post on an individual's first pull request
    pr-message: # optional

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the SeadomGames Github! I see you've made your first issue. Make sure to read the README file and the security file in order to make sure your issue meets the nessacary criteria.'
        pr-message: 'Welcome to the SeadomGames Github! I see you're making your first contributation to MirrorOS. Thank you. We rely on community devs like you to keep our projects worthwhile and up-to date. If you need anything, check out the README file and don't be afriad to ask. We rely on questions. Check out the Issues tab as well to find out what needs to be worked on.'
